// Generated by CoffeeScript 1.6.3
(function($, window) {
  var ad_count, methods, module, serialize, settings;
  module = 'ads';
  ad_count = 0;
  settings = {
    srcdoc: '',
    fallback: '',
    pushdown: false,
    refreshable: false,
    dcopt: '',
    height: '',
    is_intersticial: void 0,
    kw: $('meta[name="keywords"]').attr('content'),
    publisher: 'ng',
    site_name: '',
    sz: '300x250',
    sizes: void 0,
    tile: '',
    topic: '',
    sbtpc: '',
    slot: '',
    width: '',
    zone: '',
    zone_suffix: ''
  };
  methods = {
    init: function(options) {
      return this.each(function() {
        var $this, data, opts, parameters, params, path, rand, size;
        $this = $(this);
        data = $this.data(module);
        parameters = {};
        path = window.location.pathname.split('/');
        if (!data) {
          opts = $.extend({}, settings, $this.attr('data-ad-options'), options);
          data = {};
          if (opts.sizes) {
            rand = Math.random();
            if (rand <= opts.sizes[0][1]) {
              size = opts.sizes[0][0];
            } else {
              size = opts.sizes[1][0];
            }
          } else {
            size = opts.sz.split('x');
            if (opts.width !== '') {
              size[0] = opts.width;
            }
            if (opts.height !== '') {
              size[1] = opts.height;
            }
            size = size.join('x');
          }
          data.ad_count = ad_count;
          parameters.dcopt = opts.is_intersticial !== void 0 ? opts.is_intersticial : opts.dcopt;
          parameters.kw = opts.kw;
          parameters.publisher = opts.publisher;
          parameters.site_name = opts.site_name !== '' ? opts.site_name : (path[1] && path[1] !== 'channel' ? path[1] : 'ngc');
          parameters.tile = opts.tile === '' ? ad_count : opts.tile;
          if (opts.topic !== '') {
            parameters.topic = opts.topic;
          }
          if (opts.sbtpc !== '') {
            parameters.sbtpc = opts.sbtpc;
          }
          if (opts.slot !== '') {
            parameters.slot = opts.slot;
          }
          parameters.sz = size;
          parameters.zone = "" + (!opts.zone ? (path.length > 3 ? path[2] : 'homepage') : void 0) + opts.zone_suffix;
          data.options = opts;
          data.ad_params = parameters;
          $this.data(module, data);
          if (opts.refreshable) {
            $.fn[module].$refreshables.push(this);
          }
          ad_count += 1;
          $(window).on('stateChange', function(e) {
            var $refreshables;
            $refreshables = $.fn[module].$refreshables;
            window.clearTimeout($.fn[module].timer);
            return $.fn[module].timer = window.setTimeout(function() {
              return $refreshables.ads();
            }, 500);
          });
        }
        params = $.extend({}, data != null ? data.ad_params : void 0);
        return methods.loadAd.call($this[0], params);
      });
    },
    loadAd: function(params) {
      var $adFrame, $this, ad, adFrame, ad_base, ad_iframe, ad_img, ad_js, data, err, frame_id, opts, publisher, site_name, tile, unWrapped, zone;
      $this = $(this);
      data = $this.data(module);
      opts = data.options;
      ad_base = 'http://ad.doubleclick.net/ad';
      ad_img = "" + ad_base + "/";
      ad_iframe = "" + ad_base + "i/";
      ad_js = "" + ad_base + "j/";
      adFrame = document.createElement('iframe');
      $adFrame = $(adFrame);
      unWrapped = document.createElement('script');
      params.ord = Math.floor(1000000 * Math.random());
      publisher = params.publisher;
      delete params.publisher;
      site_name = params.site_name;
      delete params.site_name;
      zone = params.zone;
      delete params.zone;
      frame_id = 'ad_frame' + data.ad_count;
      tile = data.ad_count;
      $adFrame.attr({
        width: '100%',
        height: params.sz.split('x')[1],
        allowtransparency: true,
        id: frame_id,
        name: frame_id,
        seamless: true,
        frameborder: 0,
        src: "" + ad_iframe + publisher + "." + site_name + "/" + zone + ";" + (serialize(params))
      });
      if (opts.pushdown) {
        unWrapped.src = ad_js + serialize(params);
        ad = unWrapped;
      } else {
        try {
          $adFrame.html(fallback);
        } catch (_error) {
          err = _error;
        }
        ad = $adFrame;
      }
      return $this.html(ad);
    }
  };
  serialize = function(obj) {
    var key, params, val;
    params = (function() {
      var _results;
      _results = [];
      for (key in obj) {
        val = obj[key];
        _results.push("" + key + "=" + (encodeURI(val)));
      }
      return _results;
    })();
    return params.join(';');
  };
  $.fn[module] = function(method) {
    if (methods[method]) {
      return methods[method].apply(this, Array.prototype.slice.call(arguments, 1));
    } else if (typeof method === 'object' || !method) {
      return methods.init.apply(this, arguments);
    } else {
      return $.error("Method " + method + " does not exist on jQuery." + module);
    }
  };
  $.fn[module].$refreshables = $();
  return $.fn[module].timer = void 0;
})(jQuery, window);
